Lowlife Champions of Mosscrest: game_helper.h File Reference
game_helper.h File Reference
#include "uart.h"
#include "player.h"
#include "grid.h"
#include "i8042.h"
#include "rtc.h"
#include "enemies.h"
#include "graphics.h"
Data Structures
struct Game
Struct that holds information on ALL the current game variables, excluding the grid.
struct GameState
Struct that holds information on current gamemode, menu and difficulty.
Enumerations
enum Difficulty { EASY, MEDIUM, HARD }
Represents the in game difficulty.
enum Gamemode { SINGLEPLAYER, COOP }
Represents the gamemode the player is playing.
enum Menu {
MAIN_MENU, DIFFICULTY_MENU, SYNCING, IN_GAME,
VICTORY, LOST, EXIT
}
Represents the current game menu.
Functions
void create_enemies (struct Game game)
Generates the random enemy board on the grid.
void on_timer_int (struct Game *game)
Performs all game logic and displaying that occurs every frame depending on the game state.
void process_kbd_input (struct Game *game)
Processes the input that comes from the keyboard and executes the associated logic.
void process_mouse_input (struct Game *game)
Processes the input that comes from the mouse and executes the associated logic.
void process_uart_packet (struct Game *game)
Processes the incoming packet from the UART (COM1) and executes the associated logic.
Enumeration Type Documentation
Difficulty
enum Difficulty
Represents the in game difficulty.
Enumerator
EASY
Easy difficulty
MEDIUM
Medium difficulty
HARD
Hard difficulty
Definition at line 41 of file game_helper.h.
Gamemode
enum Gamemode
Represents the gamemode the player is playing.
Enumerator
SINGLEPLAYER
Single player mode
COOP
Coop mode
Definition at line 16 of file game_helper.h.
Menu
enum Menu
Represents the current game menu.
Enumerator
MAIN_MENU
Main menu
DIFFICULTY_MENU
Difficulty menu
SYNCING
Syncing with the other player (COOP)
IN_GAME
In game (player)
VICTORY
Victory screen
LOST
Lost screen
EXIT
EXIT game
Definition at line 26 of file game_helper.h.
Function Documentation
create_enemies()
void create_enemies (struct Game game)
Generates the random enemy board on the grid.
Parameters
game Current game state to be read
Note
For convenience, this function already generates the random game seed based on current RTC reading
Definition at line 129 of file game_helper.c.
References create_g_blob(), GameState::difficulty, Game::game_state, GameState::gamemode, grid_add(), GridX, GridY, rtc_read_time(), and SINGLEPLAYER.
Referenced by process_mouse_input(), and process_uart_packet().
on_timer_int()
void on_timer_int (struct Game * game)
Performs all game logic and displaying that occurs every frame depending on the game state.
Parameters
game Current game state to be read and updated
Definition at line 272 of file game_helper.c.
References Game::action_request_player_1, Game::action_request_player_2, Game::background_generated, background_refresh(), SpearMan::channeling_special, COOP, Game::cursor, DIFFICULTY_MENU, Entity::entity_info, EXIT, FIRST_STEP, Game::game_frame, Game::game_state, Game::gameEnded, GameState::gamemode, grid_enemies_move(), IN_GAME, LOST, MAIN_MENU, GameState::menu, menu_background, mouse_grid_pos(), paint_area(), paint_background_lateral_walls(), paint_cursor(), paint_grid(), paint_text(), paint_UI(), paint_xpm(), Game::player_1, PLAYER_1, Game::player_2, PLAYER_2, Game::player_num, rtc_alarm_occurred, spearman_act(), SPEARMAN_NO_ACT, sync_first_step(), Game::sync_frame, Game::sync_state, SYNCING, uart_com1_data, update_animations(), VICTORY, video_refresh(), and winning_background.
Referenced by proj_main_loop().
process_kbd_input()
void process_kbd_input (struct Game * game)
Processes the input that comes from the keyboard and executes the associated logic.
Parameters
game Current game state to be read and updated
Definition at line 11 of file game_helper.c.
References A_MAKE, Game::action_request_player_1, Game::action_request_player_2, Game::background_generated, BREAKC, SpearMan::channeling_special, COOP, D_MAKE, delete_grid(), DIFFICULTY_MENU, ESC_MAKE, EXIT, Game::game_state, GameState::gamemode, IN_GAME, kbd_data, LOST, MAIN_MENU, GameState::menu, Game::player_1, PLAYER_1, Game::player_2, PLAYER_2, Game::player_num, Q_MAKE, S_MAKE, send_data_uart(), SP_MAKE, SPEARMAN_ATTACK, SPEARMAN_MOVE_DOWN, SPEARMAN_MOVE_LEFT, SPEARMAN_MOVE_RIGHT, SPEARMAN_MOVE_UP, SpearMan::special_in_cd, VICTORY, and W_MAKE.
Referenced by proj_main_loop().
process_mouse_input()
void process_mouse_input (struct Game * game)
Processes the input that comes from the mouse and executes the associated logic.
Parameters
game Current game state to be read and updated
Definition at line 144 of file game_helper.c.
References Game::action_request_player_1, Game::action_request_player_2, SpearMan::channeling_special, COOP, create_background(), create_enemies(), create_spearman(), Game::cursor, GameState::difficulty, DIFFICULTY_MENU, EASY, Game::game_state, GameState::gamemode, grid_add(), HARD, IN_GAME, MAIN_MENU, MEDIUM, GameState::menu, mouse_pack, Game::player_1, PLAYER_1, Game::player_2, PLAYER_2, Game::player_num, send_data_uart(), SINGLEPLAYER, SPEARMAN_SPECIAL_DOWN, SPEARMAN_SPECIAL_LEFT, SPEARMAN_SPECIAL_RIGHT, SPEARMAN_SPECIAL_UP, SYNCING, update_mouse_position(), Cursor::x, and Cursor::y.
Referenced by proj_main_loop().
process_uart_packet()
void process_uart_packet (struct Game * game)
Processes the incoming packet from the UART (COM1) and executes the associated logic.
Parameters
game Current game state to be read and updated
Definition at line 235 of file game_helper.c.
References Game::action_request_player_1, Game::action_request_player_2, Game::background_generated, COOP, create_background(), create_enemies(), create_spearman(), delete_grid(), FIRST_STEP, Game::game_state, GameState::gamemode, grid_add(), IN_GAME, MAIN_MENU, GameState::menu, Game::player_1, PLAYER_1, Game::player_2, Game::player_num, sync_players(), Game::sync_state, SYNCING, and uart_com1_data.
Referenced by proj_main_loop().