Lowlife Champions of Mosscrest: kbd.h File Reference
kbd.h File Reference
Enumerations
enum kbd_data_status { SINGLE_READY, DOUBLE_READY, NOT_READY }
Enumerator that indicates the status of the current data read from the KBC (keyboard)
Functions
void() kbd_ih (void)
Keyboard interrupt handler.
enum kbd_data_status kbd_parse_data ()
Parses the KBC keyboard data.
int kbd_subscribe_int (uint8_t *bit_no)
Subscribes the interrupts for the Keyboard at IRQ 1.
int kbd_unsubscribe_int ()
Unsubscribes the interrupts for the Keyboard at IRQ 1.
Enumeration Type Documentation
kbd_data_status
enum kbd_data_status
Enumerator that indicates the status of the current data read from the KBC (keyboard)
Enumerator
SINGLE_READY
Single byte data available.
DOUBLE_READY
Dual byte data available.
NOT_READY
data not available
Definition at line 8 of file kbd.h.
Function Documentation
kbd_ih()
void() kbd_ih (void)
Keyboard interrupt handler.
Definition at line 26 of file kbd.c.
Referenced by proj_main_loop().
kbd_parse_data()
enum kbd_data_status kbd_parse_data ()
Parses the KBC keyboard data.
Returns
enum kbd_data_status parsed data information
Definition at line 26 of file kbd.c.
References DELAY_US, KBC_AUX, KBC_OBF, KBC_OUT_BUF, KBC_PAR_ERR, KBC_ST_REG, KBC_TO_ERR, kbd_data, read_error, and util_sys_inb().
Referenced by proj_main_loop().
kbd_subscribe_int()
int kbd_subscribe_int (uint8_t * bit_no)
Subscribes the interrupts for the Keyboard at IRQ 1.
Parameters
bit_no id of the subscription
Returns
int 1 if it fails 0 otherwise
Definition at line 14 of file kbd.c.
References IRQ_1, and kbd_hook_id.
Referenced by proj_main_loop().
kbd_unsubscribe_int()
int kbd_unsubscribe_int ()
Unsubscribes the interrupts for the Keyboard at IRQ 1.
Returns
int 1 if it fails 0 otherwise
Definition at line 20 of file kbd.c.
References kbd_hook_id.
Referenced by proj_main_loop().