Lowlife Champions of Mosscrest: entities.c File Reference
entities.c File Reference
#include <lcom/lcf.h>
#include <lcom/liblm.h>
#include <lcom/proj.h>
#include "entities.h"
#include "enemies.h"
#include "player.h"
#include "grid.h"
Functions
void delete_grid ()
Deletes the grid entities (frees memory)
int grid_add (struct Entity *entity)
Add entity to the game board.
int grid_health_mod (const uint8_t x, const uint8_t y, const char health_mod)
Modifies the HP of an Entity in position (x , y) by health_mod.
int grid_move (const uint8_t curr_x, const uint8_t curr_y, const uint8_t new_x, const uint8_t new_y)
Moves an entity from position (curr_x , curr_y) to postition (new_x, new_y)
int update_animations (const uint32_t frame)
Updates the animations of all Entities.
Function Documentation
delete_grid()
void delete_grid ()
Deletes the grid entities (frees memory)
Definition at line 109 of file entities.c.
References Entity::entity_info, grid, GridX, and GridY.
Referenced by process_kbd_input(), process_uart_packet(), and proj_main_loop().
grid_add()
int grid_add (struct Entity * entity)
Add entity to the game board.
Parameters
entity Entity to add
Returns
int 1 if that postition is aready occupied, 0 otherwise
Definition at line 21 of file entities.c.
References Entity::entity_info, GREEN_BLOB, grid, GridX, GridY, SPEARMAN, Entity::type, GreenBlob::x, SpearMan::x, GreenBlob::y, and SpearMan::y.
Referenced by create_enemies(), process_mouse_input(), and process_uart_packet().
grid_health_mod()
int grid_health_mod (const uint8_t x, const uint8_t y, const char health_mod)
Modifies the HP of an Entity in position (x , y) by health_mod.
Parameters
x Entity's X postition
y Entity's Y postition
health_mod health modification
Returns
int 1 if the health mod is not possible, 0 otherwise
Definition at line 45 of file entities.c.
References GreenBlob::action, SpearMan::curr_action, Entity::entity_info, GREEN_BLOB, GREEN_BLOB_DEAD, grid, GridX, GridY, GreenBlob::HP, SpearMan::HP, SPEARMAN, SPEARMAN_DEAD, Entity::type, GreenBlob::x, and GreenBlob::y.
Referenced by green_blob_act(), spearman_attack(), and spearman_special().
grid_move()
int grid_move (const uint8_t curr_x, const uint8_t curr_y, const uint8_t new_x, const uint8_t new_y)
Moves an entity from position (curr_x , curr_y) to postition (new_x, new_y)
Parameters
curr_x Entity's current X postition
curr_y Entity's current Y postition
new_x Entity's new X postition
new_y Entity's new Y postition
Returns
int 2 if the new postition is already occupied, 1 if the new postition is out of the board and 0 otherwise
Definition at line 10 of file entities.c.
References grid, GridX, and GridY.
Referenced by green_blob_act(), and spearman_move().
update_animations()
int update_animations (const uint32_t frame)
Updates the animations of all Entities.
Parameters
frame current frame
Returns
int 1 death animation has finished, 0 otherwise
Definition at line 80 of file entities.c.
References animate_green_blob(), animate_spearman(), Entity::entity_info, GREEN_BLOB, grid, GridX, GridY, SPEARMAN, and Entity::type.
Referenced by on_timer_int().