Lowlife Champions of Mosscrest: player.c File Reference
player.c File Reference
#include <lcom/lcf.h>
#include <lcom/liblm.h>
#include <lcom/proj.h>
#include "player.h"
#include "rtc.h"
#include "graphics.h"
Macros
#define ATTACK_NUM_OF_FRAMES 3
#define DEATH_NUM_OF_FRAMES 4
#define MOVE_NUM_OF_FRAMES 4
Functions
int animate_spearman (struct SpearMan *spearman, const uint32_t frame)
Animates the spearman according to its action.
void animate_spearman_attack (struct SpearMan *spearman, const uint32_t frame)
Animates the spearman's attack.
int animate_spearman_death (struct SpearMan *spearman, const uint32_t frame)
Animates the spearman's directional move.
void animate_spearman_move (struct SpearMan *spearman, const uint32_t frame)
Animates the spearman's directional move.
void animate_spearman_special (struct SpearMan *spearman, const uint32_t frame)
Animates the spearman's special attack.
struct Entity * create_spearman (const uint8_t x, const uint8_t y)
int spearman_act (struct SpearMan *spearman, enum SpearmanAction PA)
The spearman acts acording to action in PA.
int spearman_attack (struct SpearMan *spearman)
The spearman attacks in its direction.
int spearman_move (struct SpearMan *spearman, const enum Direction direction)
The spearman moves in direction.
int spearman_special (struct SpearMan *spearman)
The spearman uses its special ability.
Macro Definition Documentation
ATTACK_NUM_OF_FRAMES
#define ATTACK_NUM_OF_FRAMES 3
Definition at line 8 of file player.c.
DEATH_NUM_OF_FRAMES
#define DEATH_NUM_OF_FRAMES 4
Definition at line 10 of file player.c.
MOVE_NUM_OF_FRAMES
#define MOVE_NUM_OF_FRAMES 4
Definition at line 9 of file player.c.
Function Documentation
animate_spearman()
int animate_spearman (struct SpearMan * spearman, const uint32_t frame)
Animates the spearman according to its action.
Parameters
spearman spearman to animate
frame current frame
Returns
int 1 if the spearman death animation has ended, 0 otherwise
Definition at line 183 of file player.c.
References animate_spearman_attack(), animate_spearman_death(), animate_spearman_move(), animate_spearman_special(), SpearMan::curr_action, SPEARMAN_ATTACK, SPEARMAN_DEAD, SPEARMAN_MOVE_DOWN, SPEARMAN_MOVE_LEFT, SPEARMAN_MOVE_RIGHT, SPEARMAN_MOVE_UP, SPEARMAN_SPECIAL_DOWN, SPEARMAN_SPECIAL_LEFT, SPEARMAN_SPECIAL_RIGHT, and SPEARMAN_SPECIAL_UP.
Referenced by update_animations().
animate_spearman_attack()
void animate_spearman_attack (struct SpearMan * spearman, const uint32_t frame)
Animates the spearman's attack.
Parameters
spearman spearman to animate
frame current frame
Definition at line 291 of file player.c.
References ATTACK_NUM_OF_FRAMES, SpearMan::curr_action, SpearMan::current_sprite, SpearMan::d, spearman_attack_sprites, spearman_direction_sprites, and SPEARMAN_NO_ACT.
Referenced by animate_spearman().
animate_spearman_death()
int animate_spearman_death (struct SpearMan * spearman, const uint32_t frame)
Animates the spearman's directional move.
Parameters
spearman spearman to animate
frame current frame
Returns
1 if the death animation has finished, 0 otherwise
Definition at line 371 of file player.c.
References SpearMan::current_sprite, SpearMan::d, DEATH_NUM_OF_FRAMES, and spearman_death_sprites.
Referenced by animate_spearman().
animate_spearman_move()
void animate_spearman_move (struct SpearMan * spearman, const uint32_t frame)
Animates the spearman's directional move.
Parameters
spearman spearman to animate
frame current frame
Definition at line 328 of file player.c.
References SpearMan::curr_action, SpearMan::current_sprite, SpearMan::d, MOVE_NUM_OF_FRAMES, spearman_direction_sprites, SPEARMAN_NO_ACT, and spearman_walk_sprites.
Referenced by animate_spearman().
animate_spearman_special()
void animate_spearman_special (struct SpearMan * spearman, const uint32_t frame)
Animates the spearman's special attack.
Parameters
spearman spearman to animate
frame current frame
Definition at line 212 of file player.c.
References ATTACK_NUM_OF_FRAMES, SpearMan::curr_action, SpearMan::current_sprite, SpearMan::d, DOWN, LEFT, paint_xpm(), RIGHT, spearman_attack_sprites, spearman_direction_sprites, SPEARMAN_NO_ACT, spearman_special_e_w, spearman_special_n_s, SpearMan::special_range, UP, SpearMan::x, and SpearMan::y.
Referenced by animate_spearman().
create_spearman()
struct Entity* create_spearman (const uint8_t x, const uint8_t y)
Definition at line 12 of file player.c.
References SpearMan::channeling_special, SpearMan::curr_action, SpearMan::current_sprite, SpearMan::d, SpearMan::dmg, Entity::entity_info, SpearMan::HP, SpearMan::maxHP, RIGHT, SPEARMAN, spearman_direction_sprites, SPEARMAN_NO_ACT, SpearMan::special_cd, SpearMan::special_dmg, SpearMan::special_in_cd, SpearMan::special_range, SpearMan::target_x, Entity::type, SpearMan::x, and SpearMan::y.
Referenced by process_mouse_input(), and process_uart_packet().
spearman_act()
int spearman_act (struct SpearMan * spearman, enum SpearmanAction PA)
The spearman acts acording to action in PA.
Parameters
spearman spearman that will act
PA Action
Returns
int 2 if the spearman is dead, 1 if the spearman action is not permited 0 otherwise
Definition at line 89 of file player.c.
References SpearMan::channeling_special, SpearMan::curr_action, spearman_attack(), SPEARMAN_ATTACK, SPEARMAN_DEAD, spearman_move(), SPEARMAN_MOVE_DOWN, SPEARMAN_MOVE_LEFT, SPEARMAN_MOVE_RIGHT, SPEARMAN_MOVE_UP, SPEARMAN_NO_ACT, spearman_special(), SPEARMAN_SPECIAL_DOWN, SPEARMAN_SPECIAL_LEFT, SPEARMAN_SPECIAL_RIGHT, and SPEARMAN_SPECIAL_UP.
Referenced by on_timer_int().
spearman_attack()
int spearman_attack (struct SpearMan * spearman)
The spearman attacks in its direction.
Parameters
spearman spearman that will attack
Returns
int 1 if the attack fails, 0 otherwise
Definition at line 38 of file player.c.
References SpearMan::d, SpearMan::dmg, DOWN, grid_health_mod(), LEFT, RIGHT, UP, SpearMan::x, and SpearMan::y.
Referenced by spearman_act().
spearman_move()
int spearman_move (struct SpearMan * spearman, const enum Direction direction)
The spearman moves in direction.
Parameters
spearman spearman that will move
direction direction that this spearman will move
Returns
int 1 if he can not move, 0 otherwise
Definition at line 59 of file player.c.
References SpearMan::current_sprite, SpearMan::d, DOWN, grid_move(), LEFT, RIGHT, spearman_direction_sprites, UP, SpearMan::x, and SpearMan::y.
Referenced by spearman_act().
spearman_special()
int spearman_special (struct SpearMan * spearman)
The spearman uses its special ability.
Parameters
spearman spearman that will use the special
Returns
int 1 if the special ability fails, 0 otherwise
Definition at line 131 of file player.c.
References SpearMan::channeling_special, SpearMan::curr_action, SpearMan::current_sprite, SpearMan::d, DOWN, grid_health_mod(), LEFT, RIGHT, rtc_set_alarm_delta_s(), spearman_direction_sprites, SPEARMAN_SPECIAL_DOWN, SPEARMAN_SPECIAL_LEFT, SPEARMAN_SPECIAL_RIGHT, SPEARMAN_SPECIAL_UP, SpearMan::special_cd, SpearMan::special_dmg, SpearMan::special_in_cd, SpearMan::special_range, UP, SpearMan::x, and SpearMan::y.
Referenced by spearman_act().