My Project: LCOM.c File Reference
LCOM.c File Reference
#include <lcom/lcf.h>
#include <lcom/liblm.h>
#include <lcom/proj.h>
#include <stdbool.h>
#include <stdint.h>
#include "rtc.h"
#include "player.h"
#include "graphics.h"
#include "i8042.h"
#include "kbd.h"
#include "utils.h"
#include "entities.h"
#include "enemies.h"
#include "sprites/sprites.h"
#include "grid.h"
#include "mouse.h"
Functions
int main (int argc, char *argv[])
static int print_usage ()
void() kbd_ih (void)
void() mouse_ih (void)
void() rtc_ih (void)
int() proj_main_loop (int argc, char *argv[])
Variables
static bool read_error = false
static uint8_t kbd_data
static uint8_t mouse_data
Function Documentation
kbd_ih()
void() kbd_ih (void)
Definition at line 58 of file LCOM.c.
References DELAY_US, KBC_AUX, KBC_OBF, KBC_OUT_BUF, KBC_PAR_ERR, KBC_ST_REG, KBC_TO_ERR, kbd_data, read_error, and util_sys_inb().
Referenced by proj_main_loop().
main()
int main (int argc, char * argv[])
Definition at line 27 of file LCOM.c.
mouse_ih()
void() mouse_ih (void)
Definition at line 84 of file LCOM.c.
References DELAY_US, KBC_AUX, KBC_OBF, KBC_OUT_BUF, KBC_PAR_ERR, KBC_ST_REG, KBC_TO_ERR, mouse_data, read_error, and util_sys_inb().
Referenced by proj_main_loop().
print_usage()
static int print_usage () static
Definition at line 52 of file LCOM.c.
Referenced by proj_main_loop().
proj_main_loop()
int() proj_main_loop (int argc, char * argv[])
Definition at line 134 of file LCOM.c.
References A_MAKE, background_refresh(), BREAKC, create_background(), create_g_blob(), create_spearman(), D_MAKE, delete_grid(), Entity::entity_info, ESC_MAKE, grid, grid_add(), grid_enemies_move(), GridX, GridY, kbd_data, kbd_ih(), kbd_subscribe_int(), kbd_unsubscribe_int(), mouse_data, MOUSE_DIS_DATA_REP, MOUSE_EN_DATA_REP, mouse_ih(), MOUSE_STREAM, mouse_subscribe_int(), mouse_unsubscribe_int(), mouse_write_command(), paint_background_lateral_walls(), paint_grid(), print_usage(), read_error, rtc_ih(), rtc_read_register(), RTC_REG_A, RTC_REG_B, RTC_REG_C, rtc_subscribe_int(), RTC_UIE, rtc_unsubscribe_int(), rtc_write_register(), S_MAKE, SP_MAKE, spearman_act(), SPEARMAN_ATTACK, SPEARMAN_MOVE_DOWN, SPEARMAN_MOVE_LEFT, SPEARMAN_MOVE_RIGHT, SPEARMAN_MOVE_UP, SPEARMAN_NO_ACT, timer_subscribe_int(), timer_unsubscribe_int(), TWO_BYTE_SC, update_animations(), vg_exit_ours(), vg_init_ours(), video_refresh(), and W_MAKE.
rtc_ih()
void() rtc_ih (void)
Definition at line 109 of file LCOM.c.
References RTC_AF, RTC_PF, rtc_read_register(), rtc_read_time(), RTC_REG_C, and RTC_UF.
Referenced by proj_main_loop().
Variable Documentation
kbd_data
uint8_t kbd_data static
Definition at line 23 of file LCOM.c.
Referenced by kbd_ih(), and proj_main_loop().
mouse_data
uint8_t mouse_data static
Definition at line 24 of file LCOM.c.
Referenced by mouse_ih(), and proj_main_loop().
read_error
bool read_error = false static
Definition at line 22 of file LCOM.c.
Referenced by kbd_ih(), mouse_ih(), and proj_main_loop().