Lowlife Champions of Mosscrest: kbd.c File Reference
kbd.c File Reference
#include <lcom/lcf.h>
#include <lcom/liblm.h>
#include <lcom/proj.h>
#include "i8042.h"
#include "kbd.h"
Functions
void() kbd_ih (void)
Keyboard interrupt handler.
enum kbd_data_status kbd_parse_data ()
Parses the KBC keyboard data.
int() kbd_subscribe_int (uint8_t *bit_no)
Subscribes the interrupts for the Keyboard at IRQ 1.
int() kbd_unsubscribe_int ()
Unsubscribes the interrupts for the Keyboard at IRQ 1.
Variables
static uint8_t bytes [2]
static bool double_byte = false
uint8_t kbd_data
static int kbd_hook_id
static bool make
static bool read_error = false
Function Documentation
kbd_ih()
void() kbd_ih (void)
Keyboard interrupt handler.
Definition at line 26 of file kbd.c.
Referenced by proj_main_loop().
kbd_parse_data()
enum kbd_data_status kbd_parse_data ()
Parses the KBC keyboard data.
Returns
enum kbd_data_status parsed data information
Definition at line 26 of file kbd.c.
References DELAY_US, KBC_AUX, KBC_OBF, KBC_OUT_BUF, KBC_PAR_ERR, KBC_ST_REG, KBC_TO_ERR, kbd_data, read_error, and util_sys_inb().
Referenced by proj_main_loop().
kbd_subscribe_int()
int() kbd_subscribe_int (uint8_t * bit_no)
Subscribes the interrupts for the Keyboard at IRQ 1.
Parameters
bit_no id of the subscription
Returns
int 1 if it fails 0 otherwise
Definition at line 14 of file kbd.c.
References IRQ_1, and kbd_hook_id.
Referenced by proj_main_loop().
kbd_unsubscribe_int()
int() kbd_unsubscribe_int ()
Unsubscribes the interrupts for the Keyboard at IRQ 1.
Returns
int 1 if it fails 0 otherwise
Definition at line 20 of file kbd.c.
References kbd_hook_id.
Referenced by proj_main_loop().
Variable Documentation
bytes
uint8_t bytes[2] static
Definition at line 11 of file kbd.c.
double_byte
bool double_byte = false static
Definition at line 12 of file kbd.c.
kbd_data
uint8_t kbd_data
Definition at line 9 of file kbd.c.
Referenced by kbd_parse_data(), and process_kbd_input().
kbd_hook_id
int kbd_hook_id static
Definition at line 7 of file kbd.c.
Referenced by kbd_subscribe_int(), and kbd_unsubscribe_int().
make
bool make static
Definition at line 10 of file kbd.c.
read_error
bool read_error = false static
Definition at line 8 of file kbd.c.
Referenced by kbd_parse_data().