Lowlife Champions of Mosscrest: rtc.c File Reference
rtc.c File Reference
#include "rtc.h"
#include <lcom/lcf.h>
#include <lcom/liblm.h>
#include <lcom/proj.h>
#include "utils.h"
Functions
int bcd_to_binary (uint8_t *val)
Converts a number in BCD to binary.
int binary_to_bcd (uint8_t *val)
Converts a number in binary to BCD.
void() rtc_ih (void)
RTC interrupt handler.
int rtc_read_register (uint8_t reg, uint8_t *data)
Reads the Register reg of the RTC.
int rtc_read_time (uint8_t *hours, uint8_t *minutes, uint8_t *seconds)
Reads the time from the RTC.
int rtc_set_alarm (uint8_t hours, uint8_t minutes, uint8_t seconds)
Sets an alarm at hours : minutes : seconds.
int rtc_set_alarm_delta_s (uint8_t delta_seconds)
Sets an alarm at current_time + delta_seconds.
int rtc_set_periodic (uint8_t delta_t)
Sets the periodic interrupts time to send interrupts every delta_t.
int() rtc_subscribe_int (uint8_t *bit_no)
Subscribes the RTC interrupts.
int() rtc_unsubscribe_int ()
Unsubscribes the RTC interrupts.
int rtc_write_register (uint8_t reg, uint8_t data)
Writes to the Register reg of the RTC data.
Variables
bool rtc_alarm_occurred = false
static int rtc_hook_id
Function Documentation
bcd_to_binary()
int bcd_to_binary (uint8_t * val)
Converts a number in BCD to binary.
Parameters
val the value which is to be converted; also a return value
Returns
int 1 if it fails, 0 otherwise
Definition at line 110 of file rtc.c.
Referenced by rtc_set_alarm_delta_s().
binary_to_bcd()
int binary_to_bcd (uint8_t * val)
Converts a number in binary to BCD.
Parameters
val the value which is to be converted; also a return value
Returns
int 1 if the number has more than 2 digits, 0 otherwise
Definition at line 116 of file rtc.c.
Referenced by rtc_set_alarm_delta_s().
rtc_ih()
void() rtc_ih (void)
RTC interrupt handler.
Definition at line 124 of file rtc.c.
References RTC_AF, rtc_alarm_occurred, rtc_read_register(), rtc_read_time(), RTC_REG_C, and RTC_UF.
Referenced by proj_main_loop().
rtc_read_register()
int rtc_read_register (uint8_t reg, uint8_t * data)
Reads the Register reg of the RTC.
Parameters
reg register number
data return data
Returns
int 1 if it fails, 0 otherwise
Definition at line 21 of file rtc.c.
References RTC_ADDR_REG, RTC_DATA_REG, and util_sys_inb().
Referenced by proj_main_loop(), rtc_ih(), rtc_read_time(), and rtc_set_periodic().
rtc_read_time()
int rtc_read_time (uint8_t * hours, uint8_t * minutes, uint8_t * seconds)
Reads the time from the RTC.
Parameters
hours address where the current hours will be written
minutes address where the current minutes will be written
seconds address where the current seconds will be written
Returns
int 1 if it fails, 0 otherwise
Definition at line 50 of file rtc.c.
References rtc_read_register(), RTC_REG_A, RTC_REG_H, RTC_REG_M, RTC_REG_S, and RTC_UIP.
Referenced by create_enemies(), rtc_ih(), and rtc_set_alarm_delta_s().
rtc_set_alarm()
int rtc_set_alarm (uint8_t hours, uint8_t minutes, uint8_t seconds)
Sets an alarm at hours : minutes : seconds.
Parameters
hours hour to set the alarm to
minutes minute to set the alarm to
seconds second to set the alarm to
Returns
int 1 if it fails, 0 otherwise
Definition at line 39 of file rtc.c.
References RTC_REG_H_A, RTC_REG_M_A, RTC_REG_S_A, and rtc_write_register().
Referenced by rtc_set_alarm_delta_s().
rtc_set_alarm_delta_s()
int rtc_set_alarm_delta_s (uint8_t delta_seconds)
Sets an alarm at current_time + delta_seconds.
Parameters
delta_seconds the number of seconds before the alarm will trigger
Returns
int 1 if it fails, 0 otherwise
Definition at line 79 of file rtc.c.
References bcd_to_binary(), binary_to_bcd(), rtc_read_time(), and rtc_set_alarm().
Referenced by spearman_special().
rtc_set_periodic()
int rtc_set_periodic (uint8_t delta_t)
Sets the periodic interrupts time to send interrupts every delta_t.
Parameters
delta_t time corresponding to the periodic interrupt specifications
Returns
int 1 if it fails, 0 otherwise
Definition at line 68 of file rtc.c.
References rtc_read_register(), RTC_REG_A, and rtc_write_register().
rtc_subscribe_int()
int() rtc_subscribe_int (uint8_t * bit_no)
Subscribes the RTC interrupts.
Returns
1 if it fails, 0 otherwise
Definition at line 10 of file rtc.c.
References IRQ_8, and rtc_hook_id.
Referenced by proj_main_loop().
rtc_unsubscribe_int()
int() rtc_unsubscribe_int ()
Unsubscribes the RTC interrupts.
Returns
1 if it fails, 0 otherwise
Definition at line 16 of file rtc.c.
References rtc_hook_id.
Referenced by proj_main_loop().
rtc_write_register()
int rtc_write_register (uint8_t reg, uint8_t data)
Writes to the Register reg of the RTC data.
Parameters
reg register number
data writing data
Returns
int 1 if it fails, 0 otherwise
Definition at line 30 of file rtc.c.
References RTC_ADDR_REG, and RTC_DATA_REG.
Referenced by proj_main_loop(), rtc_set_alarm(), and rtc_set_periodic().
Variable Documentation
rtc_alarm_occurred
bool rtc_alarm_occurred = false
Definition at line 8 of file rtc.c.
Referenced by on_timer_int(), and rtc_ih().
rtc_hook_id
int rtc_hook_id static
Definition at line 7 of file rtc.c.
Referenced by rtc_subscribe_int(), and rtc_unsubscribe_int().