Lowlife Champions of Mosscrest: game_helper.c File Reference
game_helper.c File Reference
#include <lcom/lcf.h>
#include <lcom/liblm.h>
#include <lcom/proj.h>
#include "game_helper.h"
Functions
void create_enemies (struct Game game)
Generates the random enemy board on the grid.
void on_timer_int (struct Game *game)
Performs all game logic and displaying that occurs every frame depending on the game state.
void process_kbd_input (struct Game *game)
Processes the input that comes from the keyboard and executes the associated logic.
void process_mouse_input (struct Game *game)
Processes the input that comes from the mouse and executes the associated logic.
void process_uart_packet (struct Game *game)
Processes the incoming packet from the UART (COM1) and executes the associated logic.
Variables
uint8_t kbd_data
struct packet mouse_pack
bool rtc_alarm_occurred
uint8_t uart_com1_data
Function Documentation
create_enemies()
void create_enemies (struct Game game)
Generates the random enemy board on the grid.
Parameters
game Current game state to be read
Note
For convenience, this function already generates the random game seed based on current RTC reading
Definition at line 129 of file game_helper.c.
References create_g_blob(), GameState::difficulty, Game::game_state, GameState::gamemode, grid_add(), GridX, GridY, rtc_read_time(), and SINGLEPLAYER.
Referenced by process_mouse_input(), and process_uart_packet().
on_timer_int()
void on_timer_int (struct Game * game)
Performs all game logic and displaying that occurs every frame depending on the game state.
Parameters
game Current game state to be read and updated
Definition at line 272 of file game_helper.c.
References Game::action_request_player_1, Game::action_request_player_2, Game::background_generated, background_refresh(), SpearMan::channeling_special, COOP, Game::cursor, DIFFICULTY_MENU, Entity::entity_info, EXIT, FIRST_STEP, Game::game_frame, Game::game_state, Game::gameEnded, GameState::gamemode, grid_enemies_move(), IN_GAME, LOST, MAIN_MENU, GameState::menu, menu_background, mouse_grid_pos(), paint_area(), paint_background_lateral_walls(), paint_cursor(), paint_grid(), paint_text(), paint_UI(), paint_xpm(), Game::player_1, PLAYER_1, Game::player_2, PLAYER_2, Game::player_num, rtc_alarm_occurred, spearman_act(), SPEARMAN_NO_ACT, sync_first_step(), Game::sync_frame, Game::sync_state, SYNCING, uart_com1_data, update_animations(), VICTORY, video_refresh(), and winning_background.
Referenced by proj_main_loop().
process_kbd_input()
void process_kbd_input (struct Game * game)
Processes the input that comes from the keyboard and executes the associated logic.
Parameters
game Current game state to be read and updated
Definition at line 11 of file game_helper.c.
References A_MAKE, Game::action_request_player_1, Game::action_request_player_2, Game::background_generated, BREAKC, SpearMan::channeling_special, COOP, D_MAKE, delete_grid(), DIFFICULTY_MENU, ESC_MAKE, EXIT, Game::game_state, GameState::gamemode, IN_GAME, kbd_data, LOST, MAIN_MENU, GameState::menu, Game::player_1, PLAYER_1, Game::player_2, PLAYER_2, Game::player_num, Q_MAKE, S_MAKE, send_data_uart(), SP_MAKE, SPEARMAN_ATTACK, SPEARMAN_MOVE_DOWN, SPEARMAN_MOVE_LEFT, SPEARMAN_MOVE_RIGHT, SPEARMAN_MOVE_UP, SpearMan::special_in_cd, VICTORY, and W_MAKE.
Referenced by proj_main_loop().
process_mouse_input()
void process_mouse_input (struct Game * game)
Processes the input that comes from the mouse and executes the associated logic.
Parameters
game Current game state to be read and updated
Definition at line 144 of file game_helper.c.
References Game::action_request_player_1, Game::action_request_player_2, SpearMan::channeling_special, COOP, create_background(), create_enemies(), create_spearman(), Game::cursor, GameState::difficulty, DIFFICULTY_MENU, EASY, Game::game_state, GameState::gamemode, grid_add(), HARD, IN_GAME, MAIN_MENU, MEDIUM, GameState::menu, mouse_pack, Game::player_1, PLAYER_1, Game::player_2, PLAYER_2, Game::player_num, send_data_uart(), SINGLEPLAYER, SPEARMAN_SPECIAL_DOWN, SPEARMAN_SPECIAL_LEFT, SPEARMAN_SPECIAL_RIGHT, SPEARMAN_SPECIAL_UP, SYNCING, update_mouse_position(), Cursor::x, and Cursor::y.
Referenced by proj_main_loop().
process_uart_packet()
void process_uart_packet (struct Game * game)
Processes the incoming packet from the UART (COM1) and executes the associated logic.
Parameters
game Current game state to be read and updated
Definition at line 235 of file game_helper.c.
References Game::action_request_player_1, Game::action_request_player_2, Game::background_generated, COOP, create_background(), create_enemies(), create_spearman(), delete_grid(), FIRST_STEP, Game::game_state, GameState::gamemode, grid_add(), IN_GAME, MAIN_MENU, GameState::menu, Game::player_1, PLAYER_1, Game::player_2, Game::player_num, sync_players(), Game::sync_state, SYNCING, and uart_com1_data.
Referenced by proj_main_loop().
Variable Documentation
kbd_data
uint8_t kbd_data extern
Definition at line 9 of file kbd.c.
Referenced by process_kbd_input().
mouse_pack
struct packet mouse_pack extern
Definition at line 8 of file mouse.c.
Referenced by process_mouse_input().
rtc_alarm_occurred
bool rtc_alarm_occurred extern
Definition at line 8 of file rtc.c.
Referenced by on_timer_int().
uart_com1_data
uint8_t uart_com1_data extern
Definition at line 7 of file uart.c.
Referenced by on_timer_int(), and process_uart_packet().