Lowlife Champions of Mosscrest: uart.h File Reference
uart.h File Reference
#include <lcom/lcf.h>
Macros
#define UART_COM1_BASE_ADDR 0x3F8
UART Serial Port COM 1 base address.
#define UART_COM1_IRQ 4
UART Serial Port COM 1 IRQ line.
#define UART_DLL 0
UART divisor latch LSB.
#define UART_DLM 1
UART divisor latch MSB.
#define UART_FCR 2
UART FIFO Control Register.
#define UART_IER 1
UART Interrupt Enable Register.
#define UART_IIR 2
UART Interrupt Identification Register.
#define UART_INT_ID (BIT(1) | BIT(2) | BIT(3))
UART Interruption ID.
#define UART_INT_NOT_PEND BIT(0)
UART Interruption not pending flag.
#define UART_LCR 3
UART Line Control Register.
#define UART_LSR 5
UART Line Status Register.
#define UART_LSR_FIFO BIT(7)
UART LSR FIFO Error.
#define UART_LSR_FRAME BIT(3)
UART LSR Framing error.
#define UART_LSR_OVERRUN BIT(1)
UART LSR Overrun error.
#define UART_LSR_PARITY BIT(2)
UART LSR Parity error.
#define UART_LSR_RECEIVER BIT(0)
UART LSR received data.
#define UART_LSR_TER BIT(6)
UART LSR Transmitter Empty register.
#define UART_LSR_THRE BIT(5)
UART LSR Transmitter holding register empty.
#define UART_MCR 4
UART Modem Control Register.
#define UART_MSR 6
UART Modem Status Register.
#define UART_RBR 0
UART Receiver Buffer Register.
#define UART_RDA_INT BIT(2)
UART Received data Interrupt.
#define UART_SR 7
UART Scratchpad Register.
#define UART_THR 0
UART Transmitter Holding Register.
#define UART_THRE_INT BIT(1)
UART Transmitter Holding register empty interrupt.
Enumerations
enum Player { PLAYER_1, PLAYER_2 }
Enumerator that represents the player number (1 or 2)
enum SyncState { FIRST_STEP, SECOND_STEP }
Enumerator that represents the current syncing step/state.
Functions
void send_data_uart (const uint8_t data)
Sends a byte to the UART.
int sync_first_step (enum Player *player_num, const uint8_t uart_com1_data)
First step of syncing the players in COOP mode.
int sync_players (enum Player *player_num, enum SyncState *sync_state, const uint8_t uart_com1_data)
int sync_second_step (const enum Player player_num, const uint8_t uart_com1_data)
Second step of syncing the player in COOP mode.
int uart_com1_subscribe_int (uint8_t *bit_no)
Subscribes the interrupts for the UART COM1 serial port.
int uart_com1_unsubscribe_int ()
Unsubscribes the interrupts for the UART COM1 serial port.
void uart_ih ()
UART's interrupt handler.
Macro Definition Documentation
UART_COM1_BASE_ADDR
#define UART_COM1_BASE_ADDR 0x3F8
UART Serial Port COM 1 base address.
Definition at line 6 of file uart.h.
UART_COM1_IRQ
#define UART_COM1_IRQ 4
UART Serial Port COM 1 IRQ line.
Definition at line 36 of file uart.h.
UART_DLL
#define UART_DLL 0
UART divisor latch LSB.
Definition at line 8 of file uart.h.
UART_DLM
#define UART_DLM 1
UART divisor latch MSB.
Definition at line 9 of file uart.h.
UART_FCR
#define UART_FCR 2
UART FIFO Control Register.
Definition at line 15 of file uart.h.
UART_IER
#define UART_IER 1
UART Interrupt Enable Register.
Definition at line 13 of file uart.h.
UART_IIR
#define UART_IIR 2
UART Interrupt Identification Register.
Definition at line 14 of file uart.h.
UART_INT_ID
#define UART_INT_ID (BIT(1) | BIT(2) | BIT(3))
UART Interruption ID.
Definition at line 23 of file uart.h.
UART_INT_NOT_PEND
#define UART_INT_NOT_PEND BIT(0)
UART Interruption not pending flag.
Definition at line 22 of file uart.h.
UART_LCR
#define UART_LCR 3
UART Line Control Register.
Definition at line 16 of file uart.h.
UART_LSR
#define UART_LSR 5
UART Line Status Register.
Definition at line 18 of file uart.h.
UART_LSR_FIFO
#define UART_LSR_FIFO BIT(7)
UART LSR FIFO Error.
Definition at line 32 of file uart.h.
UART_LSR_FRAME
#define UART_LSR_FRAME BIT(3)
UART LSR Framing error.
Definition at line 31 of file uart.h.
UART_LSR_OVERRUN
#define UART_LSR_OVERRUN BIT(1)
UART LSR Overrun error.
Definition at line 29 of file uart.h.
UART_LSR_PARITY
#define UART_LSR_PARITY BIT(2)
UART LSR Parity error.
Definition at line 30 of file uart.h.
UART_LSR_RECEIVER
#define UART_LSR_RECEIVER BIT(0)
UART LSR received data.
Definition at line 28 of file uart.h.
UART_LSR_TER
#define UART_LSR_TER BIT(6)
UART LSR Transmitter Empty register.
Definition at line 34 of file uart.h.
UART_LSR_THRE
#define UART_LSR_THRE BIT(5)
UART LSR Transmitter holding register empty.
Definition at line 33 of file uart.h.
UART_MCR
#define UART_MCR 4
UART Modem Control Register.
Definition at line 17 of file uart.h.
UART_MSR
#define UART_MSR 6
UART Modem Status Register.
Definition at line 19 of file uart.h.
UART_RBR
#define UART_RBR 0
UART Receiver Buffer Register.
Definition at line 11 of file uart.h.
UART_RDA_INT
#define UART_RDA_INT BIT(2)
UART Received data Interrupt.
Definition at line 25 of file uart.h.
UART_SR
#define UART_SR 7
UART Scratchpad Register.
Definition at line 20 of file uart.h.
UART_THR
#define UART_THR 0
UART Transmitter Holding Register.
Definition at line 12 of file uart.h.
UART_THRE_INT
#define UART_THRE_INT BIT(1)
UART Transmitter Holding register empty interrupt.
Definition at line 26 of file uart.h.
Enumeration Type Documentation
Player
enum Player
Enumerator that represents the player number (1 or 2)
Enumerator
PLAYER_1
Player 1.
PLAYER_2
Player 2.
Definition at line 42 of file uart.h.
SyncState
enum SyncState
Enumerator that represents the current syncing step/state.
Enumerator
FIRST_STEP
Syncing step 1.
SECOND_STEP
Syncing step 2 and final.
Definition at line 52 of file uart.h.
Function Documentation
send_data_uart()
void send_data_uart (const uint8_t data)
Sends a byte to the UART.
Parameters
data data byte
Definition at line 53 of file uart.c.
References UART_COM1_BASE_ADDR, UART_LSR, UART_LSR_TER, UART_LSR_THRE, UART_THR, and util_sys_inb().
Referenced by process_kbd_input(), process_mouse_input(), sync_first_step(), and sync_second_step().
sync_first_step()
int sync_first_step (enum Player * player_num, const uint8_t uart_com1_data)
First step of syncing the players in COOP mode.
Parameters
player_num player number (1 or 2)
uart_com1_data Data that came from the UART
Returns
int 1 if the first step has been completed, 0 otherwise
Definition at line 69 of file uart.c.
References PLAYER_2, send_data_uart(), and uart_com1_data.
Referenced by on_timer_int(), and sync_players().
sync_players()
int sync_players (enum Player * player_num, enum SyncState * sync_state, const uint8_t uart_com1_data)
Parameters
player_num player number (1 or 2)
sync_state Current sync state
uart_com1_data Data that came from the UART
Returns
int 1 if the syncing has been completed, 0 otherwise
Definition at line 95 of file uart.c.
References FIRST_STEP, SECOND_STEP, sync_first_step(), sync_second_step(), and uart_com1_data.
Referenced by process_uart_packet().
sync_second_step()
int sync_second_step (const enum Player player_num, const uint8_t uart_com1_data)
Second step of syncing the player in COOP mode.
Parameters
player_num player number (1 or 2)
uart_com1_data Data that came from the UART
Returns
int 1 if the syncing has been completed, 0 otherwise
Definition at line 81 of file uart.c.
References PLAYER_1, PLAYER_2, send_data_uart(), and uart_com1_data.
Referenced by sync_players().
uart_com1_subscribe_int()
int uart_com1_subscribe_int (uint8_t * bit_no)
Subscribes the interrupts for the UART COM1 serial port.
Parameters
bit_no id of the subscription
Returns
int 1 if it fails, 0 otherwise
Definition at line 10 of file uart.c.
References uart_com1_hook_id, and UART_COM1_IRQ.
Referenced by proj_main_loop().
uart_com1_unsubscribe_int()
int uart_com1_unsubscribe_int ()
Unsubscribes the interrupts for the UART COM1 serial port.
Returns
int 1 if it fails, 0 otherwise
Definition at line 18 of file uart.c.
References uart_com1_hook_id.
Referenced by proj_main_loop().
uart_ih()
void uart_ih ()
UART's interrupt handler.
Definition at line 25 of file uart.c.
References UART_COM1_BASE_ADDR, uart_com1_data, UART_IIR, UART_INT_ID, UART_INT_NOT_PEND, UART_LSR, UART_LSR_FIFO, UART_LSR_RECEIVER, UART_RBR, UART_RDA_INT, uart_read_error, and util_sys_inb().
Referenced by proj_main_loop().