Lowlife Champions of Mosscrest: uart.c File Reference
uart.c File Reference
#include <lcom/lcf.h>
#include <lcom/liblm.h>
#include <lcom/proj.h>
#include "uart.h"
Functions
void send_data_uart (const uint8_t data)
Sends a byte to the UART.
int sync_first_step (enum Player *player_num, const uint8_t uart_com1_data)
First step of syncing the players in COOP mode.
int sync_players (enum Player *player_num, enum SyncState *sync_state, const uint8_t uart_com1_data)
int sync_second_step (const enum Player player_num, const uint8_t uart_com1_data)
Second step of syncing the player in COOP mode.
int uart_com1_subscribe_int (uint8_t *bit_no)
Subscribes the interrupts for the UART COM1 serial port.
int uart_com1_unsubscribe_int ()
Unsubscribes the interrupts for the UART COM1 serial port.
void uart_ih ()
UART's interrupt handler.
Variables
uint8_t uart_com1_data = 0
static int uart_com1_hook_id
bool uart_read_error = false
Function Documentation
send_data_uart()
void send_data_uart (const uint8_t data)
Sends a byte to the UART.
Parameters
data data byte
Definition at line 53 of file uart.c.
References UART_COM1_BASE_ADDR, UART_LSR, UART_LSR_TER, UART_LSR_THRE, UART_THR, and util_sys_inb().
Referenced by process_kbd_input(), process_mouse_input(), sync_first_step(), and sync_second_step().
sync_first_step()
int sync_first_step (enum Player * player_num, const uint8_t uart_com1_data)
First step of syncing the players in COOP mode.
Parameters
player_num player number (1 or 2)
uart_com1_data Data that came from the UART
Returns
int 1 if the first step has been completed, 0 otherwise
Definition at line 69 of file uart.c.
References PLAYER_2, send_data_uart(), and uart_com1_data.
Referenced by on_timer_int(), and sync_players().
sync_players()
int sync_players (enum Player * player_num, enum SyncState * sync_state, const uint8_t uart_com1_data)
Parameters
player_num player number (1 or 2)
sync_state Current sync state
uart_com1_data Data that came from the UART
Returns
int 1 if the syncing has been completed, 0 otherwise
Definition at line 95 of file uart.c.
References FIRST_STEP, SECOND_STEP, sync_first_step(), sync_second_step(), and uart_com1_data.
Referenced by process_uart_packet().
sync_second_step()
int sync_second_step (const enum Player player_num, const uint8_t uart_com1_data)
Second step of syncing the player in COOP mode.
Parameters
player_num player number (1 or 2)
uart_com1_data Data that came from the UART
Returns
int 1 if the syncing has been completed, 0 otherwise
Definition at line 81 of file uart.c.
References PLAYER_1, PLAYER_2, send_data_uart(), and uart_com1_data.
Referenced by sync_players().
uart_com1_subscribe_int()
int uart_com1_subscribe_int (uint8_t * bit_no)
Subscribes the interrupts for the UART COM1 serial port.
Parameters
bit_no id of the subscription
Returns
int 1 if it fails, 0 otherwise
Definition at line 10 of file uart.c.
References uart_com1_hook_id, and UART_COM1_IRQ.
Referenced by proj_main_loop().
uart_com1_unsubscribe_int()
int uart_com1_unsubscribe_int ()
Unsubscribes the interrupts for the UART COM1 serial port.
Returns
int 1 if it fails, 0 otherwise
Definition at line 18 of file uart.c.
References uart_com1_hook_id.
Referenced by proj_main_loop().
uart_ih()
void uart_ih ()
UART's interrupt handler.
Definition at line 25 of file uart.c.
References UART_COM1_BASE_ADDR, uart_com1_data, UART_IIR, UART_INT_ID, UART_INT_NOT_PEND, UART_LSR, UART_LSR_FIFO, UART_LSR_RECEIVER, UART_RBR, UART_RDA_INT, uart_read_error, and util_sys_inb().
Referenced by proj_main_loop().
Variable Documentation
uart_com1_data
uint8_t uart_com1_data = 0
Definition at line 7 of file uart.c.
Referenced by on_timer_int(), process_uart_packet(), sync_first_step(), sync_players(), sync_second_step(), and uart_ih().
uart_com1_hook_id
int uart_com1_hook_id static
Definition at line 6 of file uart.c.
Referenced by uart_com1_subscribe_int(), and uart_com1_unsubscribe_int().
uart_read_error
bool uart_read_error = false
Definition at line 8 of file uart.c.
Referenced by proj_main_loop(), and uart_ih().