Lowlife Champions of Mosscrest: sprites/sprites.c File Reference
sprites.c File Reference
#include <lcom/lcf.h>
#include <lcom/liblm.h>
#include <lcom/proj.h>
#include "sprites.h"
#include "../graphics.h"
#include "xpm_files/background.h"
#include "xpm_files/winning_background.h"
Functions
struct GridImage *() create_grid_image (xpm_image_t *image, const int x_offset, const int y_offset)
Create a grid image object.
void generate_board_tileset_sprites (char *path)
Generates the floor tiles of the game board.
void generate_green_blob_sprites (char *path)
generates the green blob sprites
void generate_spearman_sprites (char *path)
Generates the spearman sprites.
void generate_UI_sprites (char *path)
Generates the sprites for the game UI.
void sprite_cleanup ()
Cleans up the sprites (frees memory)
Variables
static char cpy_buff [100]
Function Documentation
create_grid_image()
struct GridImage*() create_grid_image (xpm_image_t * image, const int x_offset, const int y_offset)
Create a grid image object.
Parameters
image xpm sprite already decoded
x_offset x offset for the sprite related to the grid position
y_offset y offset for the sprite related to the grid position
Returns
struct GridImage*
Definition at line 9 of file sprites.c.
References GridImage::image, GridImage::x_offset, and GridImage::y_offset.
Referenced by generate_green_blob_sprites(), and generate_spearman_sprites().
generate_board_tileset_sprites()
void generate_board_tileset_sprites (char * path)
Generates the floor tiles of the game board.
Parameters
path string that has the main path to the folder to the xpm files
Definition at line 21 of file sprites.c.
References cpy_buff, e_wall, file_to_xpm(), floor_tile_1, floor_tile_2, floor_tile_3, floor_tile_shadow, n_wall, n_wall_shadow, n_wall_top, ne_corner, nw_corner, s_wall, se_corner, sw_corner, and w_wall.
Referenced by proj_main_loop().
generate_green_blob_sprites()
void generate_green_blob_sprites (char * path)
generates the green blob sprites
Parameters
path string that has the main path to the folder to the xpm files
Definition at line 541 of file sprites.c.
References cpy_buff, create_grid_image(), file_to_xpm(), green_blob_attack_sprites, green_blob_death_sprites, green_blob_idle_sprites, green_blob_move_sprites, NUM_OF_GREEN_BLOB_ATTACK_SPRITES, NUM_OF_GREEN_BLOB_DEATH_SPRITES, NUM_OF_GREEN_BLOB_DIRECTIONS, NUM_OF_GREEN_BLOB_IDLE_SPITES, NUM_OF_GREEN_BLOB_MOVE_SPRITES, spearman_special_e_w, and spearman_special_n_s.
Referenced by proj_main_loop().
generate_spearman_sprites()
void generate_spearman_sprites (char * path)
Generates the spearman sprites.
Parameters
path string that has the main path to the folder to the xpm files
Definition at line 69 of file sprites.c.
References cpy_buff, create_grid_image(), file_to_xpm(), NUM_OF_SPEARMAN_ATTACK_SPRITES, NUM_OF_SPEARMAN_DEATH_SPRITES, NUM_OF_SPEARMAN_DIRECTIONS, NUM_OF_SPEARMAN_MOVE_SPRITES, spearman_attack_sprites, spearman_death_sprites, spearman_direction_sprites, and spearman_walk_sprites.
Referenced by proj_main_loop().
generate_UI_sprites()
void generate_UI_sprites (char * path)
Generates the sprites for the game UI.
Parameters
path string that has the main path to the folder to the xpm files
Definition at line 737 of file sprites.c.
References comma, cpy_buff, exclamation_mark, file_to_xpm(), final_stop, menu_background, mouse_cursor, NUM_OF_LETTERS, one, question_mark, spearman_special_UI, special_range_border, special_range_selected_border, UI_empty_heart, UI_full_heart, upper_letters, winning_background, and zero.
Referenced by proj_main_loop().
sprite_cleanup()
void sprite_cleanup ()
Cleans up the sprites (frees memory)
Definition at line 882 of file sprites.c.
References comma, exclamation_mark, final_stop, green_blob_attack_sprites, green_blob_death_sprites, green_blob_idle_sprites, green_blob_move_sprites, GridImage::image, menu_background, mouse_cursor, NUM_OF_GREEN_BLOB_ATTACK_SPRITES, NUM_OF_GREEN_BLOB_DEATH_SPRITES, NUM_OF_GREEN_BLOB_DIRECTIONS, NUM_OF_GREEN_BLOB_IDLE_SPITES, NUM_OF_GREEN_BLOB_MOVE_SPRITES, NUM_OF_LETTERS, NUM_OF_SPEARMAN_ATTACK_SPRITES, NUM_OF_SPEARMAN_DIRECTIONS, NUM_OF_SPEARMAN_MOVE_SPRITES, question_mark, spearman_attack_sprites, spearman_direction_sprites, spearman_special_e_w, spearman_special_n_s, spearman_special_UI, spearman_walk_sprites, special_range_border, special_range_selected_border, UI_empty_heart, UI_full_heart, upper_letters, and winning_background.
Referenced by proj_main_loop().
Variable Documentation
cpy_buff
char cpy_buff[100] static
Definition at line 9 of file sprites.c.
Referenced by generate_board_tileset_sprites(), generate_green_blob_sprites(), generate_spearman_sprites(), and generate_UI_sprites().