Lowlife Champions of Mosscrest: graphics.c File Reference
graphics.c File Reference
#include <lcom/lcf.h>
#include <lcom/liblm.h>
#include <lcom/proj.h>
#include <stdio.h>
#include <string.h>
#include "graphics.h"
#include "player.h"
#include "enemies.h"
#include "grid.h"
Macros
#define INVISIBLE 0xFF00DC
#define RGB(r, g, b) (r << 16 | g << 8 | b)
#define SET_VBE_MODE 0x02
#define V_RES_OFFSET_TILES 24
#define VBE_FUNC 0x4F
Functions
void background_refresh ()
Refreshes the background to be displayed.
int create_background ()
Generates a new background (including UI background)
struct Cursor * create_cursor ()
Create a cursor object.
int file_to_xpm (const char *filepath, xpm_image_t *img)
Generates a struct containing all the information regarding a XPM in img.
int mouse_grid_pos (struct Cursor *c, uint8_t *x_grid, uint8_t *y_grid)
Calculates the grid position of the cursor.
int paint_area (const uint16_t start_x, const uint16_t start_y, const uint16_t width, const uint16_t height, const uint32_t colour, const bool background)
Fills an area of the screen.
int paint_background_lateral_walls ()
Prints the lateral walls of the game board.
int paint_cursor (struct Cursor *c)
Paints the Cursor.
int paint_grid ()
Paints the entities of the game (playes, monsters, etc)
int paint_pixel (const uint16_t x, const uint16_t y, const uint32_t colour, bool background)
Paints a pixel in coordinates (x , y) with colour.
int paint_text (const char *s, const uint16_t x, const uint16_t y, bool background)
Paints in the screen s.
int paint_UI (struct SpearMan *s)
Paints the UI elements to the screen.
int paint_xpm (const xpm_image_t *img, const uint16_t start_x, const uint16_t start_y, bool background)
Paints a XPM file in the screen at coordinates (start_x , start_y)
void update_mouse_position (struct Cursor *c, const int16_t delta_x, const int16_t delta_y)
Updates the mouse position.
int vg_exit_ours ()
Disable the graphics mode and frees the video mem alocated as well as the buffer.
int vg_init_ours ()
Enable minix graphics mode in mode 0x14C.
void video_refresh ()
Refreshes the screen.
Variables
static int * background_buffer
static unsigned bits_per_pixel
static int * buffer
static unsigned h_res
static const uint8_t tile_size = 32
static unsigned v_res
static int * video_mem
Macro Definition Documentation
INVISIBLE
#define INVISIBLE 0xFF00DC
Definition at line 13 of file graphics.c.
RGB
#define RGB (r, g, b) (r << 16 | g << 8 | b)
Definition at line 11 of file graphics.c.
SET_VBE_MODE
#define SET_VBE_MODE 0x02
Definition at line 16 of file graphics.c.
V_RES_OFFSET_TILES
#define V_RES_OFFSET_TILES 24
Definition at line 18 of file graphics.c.
VBE_FUNC
#define VBE_FUNC 0x4F
Definition at line 15 of file graphics.c.
Function Documentation
background_refresh()
void background_refresh ()
Refreshes the background to be displayed.
Definition at line 255 of file graphics.c.
References background_buffer, bits_per_pixel, buffer, h_res, and v_res.
Referenced by on_timer_int().
create_background()
int create_background ()
Generates a new background (including UI background)
Note
this function normaly does not fail since this printing is done in a controlled loop
Definition at line 68 of file graphics.c.
References floor_tile_1, floor_tile_2, floor_tile_3, floor_tile_shadow, h_res, n_wall, n_wall_shadow, n_wall_top, ne_corner, nw_corner, paint_area(), paint_xpm(), s_wall, se_corner, sw_corner, tile_size, v_res, V_RES_OFFSET_TILES, Cursor::x, and Cursor::y.
Referenced by process_mouse_input(), and process_uart_packet().
create_cursor()
struct Cursor* create_cursor ()
Create a cursor object.
Returns
struct Cursor*
Definition at line 30 of file graphics.c.
References c.
Referenced by proj_main_loop().
file_to_xpm()
int file_to_xpm (const char * filepath, xpm_image_t * img)
Generates a struct containing all the information regarding a XPM in img.
Parameters
filepath .xpm file file path
img return value regarding this XPM file
Returns
int 1 if the file does not exist
int 2 the file read is not valid or has a invalid format
int 0 if it works
Definition at line 323 of file graphics.c.
Referenced by generate_board_tileset_sprites(), generate_green_blob_sprites(), generate_spearman_sprites(), and generate_UI_sprites().
mouse_grid_pos()
int mouse_grid_pos (struct Cursor * c, uint8_t * x_grid, uint8_t * y_grid)
Calculates the grid position of the cursor.
Parameters
c Cursor from which to calculate the position
x_grid address to write the x position of the cursor in the grid
y_grid address to write the y position of the cursor in the grid
Returns
int 1 if the mouse is out of bounds, 0 otherwise
Definition at line 51 of file graphics.c.
References c, h_res, tile_size, v_res, and V_RES_OFFSET_TILES.
Referenced by on_timer_int().
paint_area()
int paint_area (const uint16_t start_x, const uint16_t start_y, const uint16_t width, const uint16_t height, const uint32_t colour, const bool background)
Fills an area of the screen.
Parameters
start_x Horizontal coordinate
start_y Vertical coordinate
width Width to be painted (left)
height Heidht to be painted (downwards)
colour Colour to be painted
background true if the pixel will be painted in the background buffer false otherwise
Returns
int 1 it it can not fill that area, 0 otherwise
Definition at line 386 of file graphics.c.
References h_res, paint_pixel(), v_res, GreenBlob::x, and GreenBlob::y.
Referenced by create_background(), and on_timer_int().
paint_background_lateral_walls()
int paint_background_lateral_walls ()
Prints the lateral walls of the game board.
Returns
int 1 if it fails 0 otherwise
Note
this function normaly does not fail since this printing is done in a controlled loop
Definition at line 152 of file graphics.c.
References e_wall, h_res, paint_xpm(), tile_size, v_res, V_RES_OFFSET_TILES, w_wall, and Cursor::y.
Referenced by on_timer_int().
paint_cursor()
int paint_cursor (struct Cursor * c)
Paints the Cursor.
Parameters
c cursor to be painted
Returns
int 1 if it fails, 0 otherwise
Definition at line 61 of file graphics.c.
References c, mouse_cursor, and paint_xpm().
Referenced by on_timer_int().
paint_grid()
int paint_grid ()
Paints the entities of the game (playes, monsters, etc)
Returns
int 1 if it fails 0 otherwise
Definition at line 164 of file graphics.c.
References GreenBlob::current_sprite, SpearMan::current_sprite, Entity::entity_info, GREEN_BLOB, grid, GridX, GridY, GridImage::image, paint_xpm(), SPEARMAN, tile_size, Entity::type, GreenBlob::x, Cursor::x, SpearMan::x, GridImage::x_offset, GreenBlob::y, Cursor::y, SpearMan::y, and GridImage::y_offset.
Referenced by on_timer_int().
paint_pixel()
int paint_pixel (const uint16_t x, const uint16_t y, const uint32_t colour, const bool background)
Paints a pixel in coordinates (x , y) with colour.
Parameters
x Horizontal coordinate
y Vertical coordinate
colour 32 bit colour
background true if the pixel will be painted in the background buffer false otherwise
Returns
int 1 if it is impossible to paint that pixel 0 otherwise
Definition at line 311 of file graphics.c.
References background_buffer, buffer, h_res, v_res, GreenBlob::x, and GreenBlob::y.
Referenced by paint_area(), and paint_xpm().
paint_text()
int paint_text (const char * s, const uint16_t x, const uint16_t y, bool background)
Paints in the screen s.
Parameters
s string to print
x Base X value
y Base Y value
background true if the text will be painted in the background layer, false otherwise
Returns
int 1 if it fails, 0 otherwise
Note
NOT ALL CHARACTERS ARE ACCEPTED - only uppercase and symbols like ',' '.' '!' '?' are
Definition at line 265 of file graphics.c.
References comma, exclamation_mark, final_stop, one, paint_xpm(), question_mark, upper_letters, GreenBlob::x, GreenBlob::y, and zero.
Referenced by on_timer_int(), and paint_UI().
paint_UI()
int paint_UI (struct SpearMan * s)
Paints the UI elements to the screen.
Parameters
s spearman to paint UI
Returns
int 1 if it fails, 0 otherwise
Definition at line 198 of file graphics.c.
References SpearMan::channeling_special, GridX, GridY, GreenBlob::HP, SpearMan::maxHP, paint_text(), paint_xpm(), spearman_special_UI, SpearMan::special_in_cd, SpearMan::special_range, special_range_border, special_range_selected_border, SpearMan::target_x, SpearMan::target_y, tile_size, UI_empty_heart, UI_full_heart, v_res, GreenBlob::x, SpearMan::x, GreenBlob::y, and SpearMan::y.
Referenced by on_timer_int().
paint_xpm()
int paint_xpm (const xpm_image_t * img, const uint16_t start_x, const uint16_t start_y, const bool background)
Paints a XPM file in the screen at coordinates (start_x , start_y)
Parameters
img XPM struct that contains all the information regarding a xpm image
start_x Horizontal coordinate
start_y Vertical coordinate
background true if the pixel will be painted in the background buffer false otherwise
Returns
int 1 if it is not possible to paint the XPM in the space available
Definition at line 366 of file graphics.c.
References h_res, INVISIBLE, paint_pixel(), RGB, v_res, GreenBlob::x, and GreenBlob::y.
Referenced by animate_spearman_special(), create_background(), on_timer_int(), paint_background_lateral_walls(), paint_cursor(), paint_grid(), paint_text(), and paint_UI().
update_mouse_position()
void update_mouse_position (struct Cursor * c, const int16_t delta_x, const int16_t delta_y)
Updates the mouse position.
Parameters
c cursor to make the changes on
delta_x change to the x value of the mouse
delta_y change to the y value of the mouse
Definition at line 39 of file graphics.c.
References c, h_res, mouse_cursor, and v_res.
Referenced by process_mouse_input().
vg_exit_ours()
int vg_exit_ours ()
Disable the graphics mode and frees the video mem alocated as well as the buffer.
Returns
int 1 if it fails 0 otherwise
Definition at line 445 of file graphics.c.
References background_buffer, buffer, and video_mem.
Referenced by proj_main_loop().
vg_init_ours()
int vg_init_ours ()
Enable minix graphics mode in mode 0x14C.
Returns
int 1 if this process failed 0 otherwise
Definition at line 401 of file graphics.c.
References background_buffer, bits_per_pixel, buffer, h_res, SET_VBE_MODE, v_res, VBE_FUNC, and video_mem.
Referenced by proj_main_loop().
video_refresh()
void video_refresh ()
Refreshes the screen.
Definition at line 260 of file graphics.c.
References bits_per_pixel, buffer, h_res, v_res, and video_mem.
Referenced by on_timer_int().
Variable Documentation
background_buffer
int* background_buffer static
Definition at line 22 of file graphics.c.
Referenced by background_refresh(), paint_pixel(), vg_exit_ours(), and vg_init_ours().
bits_per_pixel
unsigned bits_per_pixel static
Definition at line 26 of file graphics.c.
Referenced by background_refresh(), vg_init_ours(), and video_refresh().
buffer
int* buffer static
Definition at line 21 of file graphics.c.
Referenced by background_refresh(), paint_pixel(), vg_exit_ours(), vg_init_ours(), and video_refresh().
h_res
unsigned h_res static
Definition at line 24 of file graphics.c.
Referenced by background_refresh(), create_background(), mouse_grid_pos(), paint_area(), paint_background_lateral_walls(), paint_pixel(), paint_xpm(), update_mouse_position(), vg_init_ours(), and video_refresh().
tile_size
const uint8_t tile_size = 32 static
Definition at line 28 of file graphics.c.
Referenced by create_background(), mouse_grid_pos(), paint_background_lateral_walls(), paint_grid(), and paint_UI().
v_res
unsigned v_res static
Definition at line 25 of file graphics.c.
Referenced by background_refresh(), create_background(), mouse_grid_pos(), paint_area(), paint_background_lateral_walls(), paint_pixel(), paint_UI(), paint_xpm(), update_mouse_position(), vg_init_ours(), and video_refresh().
video_mem
int* video_mem static
Definition at line 20 of file graphics.c.
Referenced by vg_exit_ours(), vg_init_ours(), and video_refresh().