Lowlife Champions of Mosscrest: enemies.h File Reference
enemies.h File Reference
#include <lcom/lcf.h>
#include "entities.h"
Data Structures
struct GreenBlob
Enemy green blob (green slime) structure.
Enumerations
enum GreenBlobAction {
GREEN_BLOB_MOVE_RIGHT, GREEN_BLOB_MOVE_UP, GREEN_BLOB_MOVE_LEFT, GREEN_BLOB_MOVE_DOWN,
GREEN_BLOB_ATTACK, GREEN_BLOB_NO_ACT, GREEN_BLOB_DEAD
}
Enumerator that represents the state of a blob.
Functions
void animate_green_blob (struct GreenBlob *gb, const uint32_t frame)
Animates the green blobs depending on their current action.
void animate_green_blob_attack (struct GreenBlob *gb, const uint32_t frame)
Animates the green blobs attacking.
void animate_green_blob_death (struct GreenBlob *gb, const uint32_t frame)
Animates the green blobs dying.
void animate_green_blob_idle (struct GreenBlob *gb, const uint32_t frame)
Animates the green blobs idle state.
void animate_green_blob_move (struct GreenBlob *gb, const uint32_t frame)
Animates the green blobs moving state.
struct Entity * create_g_blob (uint8_t x, uint8_t y, enum Direction movement)
Create a green blob object (entity)
int green_blob_act (struct GreenBlob *green_blob)
Makes the blob act (move or attack)
int grid_enemies_move ()
Moves every enemy in the grid.
Enumeration Type Documentation
GreenBlobAction
enum GreenBlobAction
Enumerator that represents the state of a blob.
Enumerator
GREEN_BLOB_MOVE_RIGHT
Moving right
GREEN_BLOB_MOVE_UP
Moving upwards
GREEN_BLOB_MOVE_LEFT
Moving left
GREEN_BLOB_MOVE_DOWN
Moving downwards
GREEN_BLOB_ATTACK
Attacking
GREEN_BLOB_NO_ACT
Idle
GREEN_BLOB_DEAD
Dead
Definition at line 11 of file enemies.h.
Function Documentation
animate_green_blob()
void animate_green_blob (struct GreenBlob * gb, const uint32_t frame)
Animates the green blobs depending on their current action.
Parameters
gb green blob to animate
frame current frame
Definition at line 113 of file enemies.c.
References GreenBlob::action, animate_green_blob_attack(), animate_green_blob_death(), animate_green_blob_idle(), animate_green_blob_move(), GREEN_BLOB_ATTACK, GREEN_BLOB_DEAD, GREEN_BLOB_MOVE_DOWN, GREEN_BLOB_MOVE_LEFT, GREEN_BLOB_MOVE_RIGHT, GREEN_BLOB_MOVE_UP, and GREEN_BLOB_NO_ACT.
Referenced by update_animations().
animate_green_blob_attack()
void animate_green_blob_attack (struct GreenBlob * gb, const uint32_t frame)
Animates the green blobs attacking.
Parameters
gb green blob to animate
frame current frame
Definition at line 235 of file enemies.c.
References GreenBlob::action, GreenBlob::current_sprite, GreenBlob::direction, GREEN_BLOB_ATTACK_NUMBER_OF_FRAMES, green_blob_attack_sprites, green_blob_idle_sprites, and GREEN_BLOB_NO_ACT.
Referenced by animate_green_blob().
animate_green_blob_death()
void animate_green_blob_death (struct GreenBlob * gb, const uint32_t frame)
Animates the green blobs dying.
Parameters
gb green blob to animate
frame current frame
Definition at line 194 of file enemies.c.
References GreenBlob::current_sprite, GREEN_BLOB_DEATH_NUMBER_OF_FRAMES, green_blob_death_sprites, grid, GreenBlob::x, and GreenBlob::y.
Referenced by animate_green_blob().
animate_green_blob_idle()
void animate_green_blob_idle (struct GreenBlob * gb, const uint32_t frame)
Animates the green blobs idle state.
Parameters
gb green blob to animate
frame current frame
Definition at line 136 of file enemies.c.
References GreenBlob::current_sprite, GREEN_BLOB_IDLE_NUMBER_OF_FRAMES, and green_blob_idle_sprites.
Referenced by animate_green_blob().
animate_green_blob_move()
void animate_green_blob_move (struct GreenBlob * gb, const uint32_t frame)
Animates the green blobs moving state.
Parameters
gb green blob to animate
frame current frame
Definition at line 157 of file enemies.c.
References GreenBlob::action, GreenBlob::current_sprite, green_blob_idle_sprites, GREEN_BLOB_MOVE_NUMBER_OF_FRAMES, green_blob_move_sprites, and GREEN_BLOB_NO_ACT.
Referenced by animate_green_blob().
create_g_blob()
struct Entity* create_g_blob (uint8_t x, uint8_t y, enum Direction movement)
Create a green blob object (entity)
Parameters
x X position on the grid
y Y position on the grid
movement Inicial orientation of the blob
Returns
struct Entity*
Definition at line 12 of file enemies.c.
References GreenBlob::action, GreenBlob::current_sprite, GreenBlob::direction, GreenBlob::dmg, Entity::entity_info, GREEN_BLOB, green_blob_idle_sprites, GREEN_BLOB_NO_ACT, GreenBlob::HP, Entity::type, GreenBlob::x, and GreenBlob::y.
Referenced by create_enemies().
green_blob_act()
int green_blob_act (struct GreenBlob * green_blob)
Makes the blob act (move or attack)
Parameters
green_blob green blob that will act
Returns
int 0 if it does not fail, 1 if it fails, 2 if the blob is dead and no action is possible
Note
The blobs always move in clockwise motion, if the blob can not move in the desired direction it will attack
Definition at line 30 of file enemies.c.
References GreenBlob::action, GreenBlob::direction, GreenBlob::dmg, DOWN, GREEN_BLOB_ATTACK, GREEN_BLOB_DEAD, GREEN_BLOB_MOVE_DOWN, GREEN_BLOB_MOVE_LEFT, GREEN_BLOB_MOVE_RIGHT, GREEN_BLOB_MOVE_UP, GREEN_BLOB_NO_ACT, grid, grid_health_mod(), grid_move(), LEFT, RIGHT, SPEARMAN, Entity::type, UP, GreenBlob::x, and GreenBlob::y.
Referenced by grid_enemies_move().
grid_enemies_move()
int grid_enemies_move ()
Moves every enemy in the grid.
Returns
int 1 if no enemies are moved, 0 otherwise
Definition at line 83 of file enemies.c.
References Entity::entity_info, GREEN_BLOB, green_blob_act(), grid, GridX, GridY, and Entity::type.
Referenced by on_timer_int().