Lowlife Champions of Mosscrest: mouse.c File Reference
mouse.c File Reference
#include <lcom/lcf.h>
#include <lcom/liblm.h>
#include <lcom/proj.h>
#include <stdint.h>
#include "mouse.h"
Functions
int() kbc_write_command (uint8_t cmd)
Writes cmd to the KBC.
void() mouse_ih (void)
Mouse interrupt handler.
int mouse_parse_data ()
Parses the data into a packet.
int() mouse_subscribe_int (uint8_t *bit_no)
Subscribes interrupts for the mouse.
int() mouse_unsubscribe_int ()
Unsubscribes interrupts for the mouse.
int() mouse_write_command (uint8_t cmd)
Writes cmd to the mouse.
Variables
static uint8_t mouse_byte = 0
static uint8_t mouse_data
static int mouse_hook_id
struct packet mouse_pack
static bool read_error = false
Function Documentation
kbc_write_command()
int() kbc_write_command (uint8_t cmd)
Writes cmd to the KBC.
Parameters
cmd command to be writen
Definition at line 26 of file mouse.c.
References DELAY_US, KBC_CTRL_REG, KBC_IBF, KBC_ST_REG, and util_sys_inb().
Referenced by mouse_write_command().
mouse_ih()
void() mouse_ih (void)
Mouse interrupt handler.
Definition at line 61 of file mouse.c.
References DELAY_US, KBC_AUX, KBC_OBF, KBC_OUT_BUF, KBC_PAR_ERR, KBC_ST_REG, KBC_TO_ERR, mouse_data, read_error, and util_sys_inb().
Referenced by proj_main_loop().
mouse_parse_data()
int mouse_parse_data ()
Parses the data into a packet.
Returns
int 1 if it fails or the packet is not complete, 0 otherwise
Definition at line 86 of file mouse.c.
References mouse_byte, mouse_data, mouse_pack, and read_error.
Referenced by proj_main_loop().
mouse_subscribe_int()
int() mouse_subscribe_int (uint8_t * bit_no)
Subscribes interrupts for the mouse.
Returns
1 if it fails, 0 otherwise
Definition at line 13 of file mouse.c.
References IRQ_12, and mouse_hook_id.
Referenced by proj_main_loop().
mouse_unsubscribe_int()
int() mouse_unsubscribe_int ()
Unsubscribes interrupts for the mouse.
Returns
1 if it fails, 0 otherwise
Definition at line 20 of file mouse.c.
References mouse_hook_id.
Referenced by proj_main_loop().
mouse_write_command()
int() mouse_write_command (uint8_t cmd)
Writes cmd to the mouse.
Parameters
cmd command to be writen
Definition at line 42 of file mouse.c.
References DELAY_US, KBC_IBF, KBC_IN_BUF, KBC_OUT_BUF, KBC_ST_REG, kbc_write_command(), KBC_WRITE_M, MOUSE_ACK, and util_sys_inb().
Referenced by proj_main_loop().
Variable Documentation
mouse_byte
uint8_t mouse_byte = 0 static
Definition at line 11 of file mouse.c.
Referenced by mouse_parse_data().
mouse_data
uint8_t mouse_data static
Definition at line 10 of file mouse.c.
Referenced by mouse_ih(), and mouse_parse_data().
mouse_hook_id
int mouse_hook_id static
Definition at line 7 of file mouse.c.
Referenced by mouse_subscribe_int(), and mouse_unsubscribe_int().
mouse_pack
struct packet mouse_pack
Definition at line 8 of file mouse.c.
Referenced by mouse_parse_data(), and process_mouse_input().
read_error
bool read_error = false static
Definition at line 8 of file mouse.c.
Referenced by mouse_ih(), and mouse_parse_data().