Lowlife Champions of Mosscrest: rtc.h File Reference
rtc.h File Reference
#include <minix/sysutil.h>
Macros
#define IRQ_8 0x08
RTC IRQ line.
#define RTC_ADDR_REG 0x70
RTC address register.
#define RTC_AF BIT(5)
Alarm interrupt pending.
#define RTC_AIE BIT(5)
Enable alarm interrupt.
#define RTC_DATA_REG 0x71
RTC data register.
#define RTC_PF BIT(6)
Periodic interrupt pending.
#define RTC_PIE BIT(6)
Enable periodic interrupts.
#define RTC_REG_A 10
RTC register A.
#define RTC_REG_B 11
RTC register B.
#define RTC_REG_C 12
RTC register C.
#define RTC_REG_H 4
RTC hours register.
#define RTC_REG_H_A 5
RTC alarm hours register.
#define RTC_REG_M 2
RTC minutes register.
#define RTC_REG_M_A 3
RTC alarm minutes register.
#define RTC_REG_S 0
RTC seconds register.
#define RTC_REG_S_A 1
RTC alarm seconds register.
#define RTC_UF BIT(4)
Update interrupt pending.
#define RTC_UIE BIT(4)
Enable update interrupts.
#define RTC_UIP BIT(7)
Update in progress.
Functions
int bcd_to_binary (uint8_t *val)
Converts a number in BCD to binary.
int binary_to_bcd (uint8_t *val)
Converts a number in binary to BCD.
void() rtc_ih (void)
RTC interrupt handler.
int rtc_read_register (uint8_t reg, uint8_t *data)
Reads the Register reg of the RTC.
int rtc_read_time (uint8_t *hours, uint8_t *minutes, uint8_t *seconds)
Reads the time from the RTC.
int rtc_set_alarm (uint8_t hours, uint8_t minutes, uint8_t seconds)
Sets an alarm at hours : minutes : seconds.
int rtc_set_alarm_delta_s (uint8_t delta_seconds)
Sets an alarm at current_time + delta_seconds.
int rtc_set_periodic (uint8_t delta_t)
Sets the periodic interrupts time to send interrupts every delta_t.
int() rtc_subscribe_int (uint8_t *bit_no)
Subscribes the RTC interrupts.
int() rtc_unsubscribe_int ()
Unsubscribes the RTC interrupts.
int rtc_write_register (uint8_t reg, uint8_t data)
Writes to the Register reg of the RTC data.
Macro Definition Documentation
IRQ_8
#define IRQ_8 0x08
RTC IRQ line.
Definition at line 6 of file rtc.h.
RTC_ADDR_REG
#define RTC_ADDR_REG 0x70
RTC address register.
Definition at line 7 of file rtc.h.
RTC_AF
#define RTC_AF BIT(5)
Alarm interrupt pending.
Definition at line 10 of file rtc.h.
RTC_AIE
#define RTC_AIE BIT(5)
Enable alarm interrupt.
Definition at line 25 of file rtc.h.
RTC_DATA_REG
#define RTC_DATA_REG 0x71
RTC data register.
Definition at line 8 of file rtc.h.
RTC_PF
#define RTC_PF BIT(6)
Periodic interrupt pending.
Definition at line 11 of file rtc.h.
RTC_PIE
#define RTC_PIE BIT(6)
Enable periodic interrupts.
Definition at line 26 of file rtc.h.
RTC_REG_A
#define RTC_REG_A 10
RTC register A.
Definition at line 13 of file rtc.h.
RTC_REG_B
#define RTC_REG_B 11
RTC register B.
Definition at line 14 of file rtc.h.
RTC_REG_C
#define RTC_REG_C 12
RTC register C.
Definition at line 15 of file rtc.h.
RTC_REG_H
#define RTC_REG_H 4
RTC hours register.
Definition at line 18 of file rtc.h.
RTC_REG_H_A
#define RTC_REG_H_A 5
RTC alarm hours register.
Definition at line 17 of file rtc.h.
RTC_REG_M
#define RTC_REG_M 2
RTC minutes register.
Definition at line 20 of file rtc.h.
RTC_REG_M_A
#define RTC_REG_M_A 3
RTC alarm minutes register.
Definition at line 19 of file rtc.h.
RTC_REG_S
#define RTC_REG_S 0
RTC seconds register.
Definition at line 22 of file rtc.h.
RTC_REG_S_A
#define RTC_REG_S_A 1
RTC alarm seconds register.
Definition at line 21 of file rtc.h.
RTC_UF
#define RTC_UF BIT(4)
Update interrupt pending.
Definition at line 9 of file rtc.h.
RTC_UIE
#define RTC_UIE BIT(4)
Enable update interrupts.
Definition at line 24 of file rtc.h.
RTC_UIP
#define RTC_UIP BIT(7)
Update in progress.
Definition at line 12 of file rtc.h.
Function Documentation
bcd_to_binary()
int bcd_to_binary (uint8_t * val)
Converts a number in BCD to binary.
Parameters
val the value which is to be converted; also a return value
Returns
int 1 if it fails, 0 otherwise
Definition at line 110 of file rtc.c.
Referenced by rtc_set_alarm_delta_s().
binary_to_bcd()
int binary_to_bcd (uint8_t * val)
Converts a number in binary to BCD.
Parameters
val the value which is to be converted; also a return value
Returns
int 1 if the number has more than 2 digits, 0 otherwise
Definition at line 116 of file rtc.c.
Referenced by rtc_set_alarm_delta_s().
rtc_ih()
void() rtc_ih (void)
RTC interrupt handler.
Definition at line 124 of file rtc.c.
References RTC_AF, rtc_alarm_occurred, rtc_read_register(), rtc_read_time(), RTC_REG_C, and RTC_UF.
Referenced by proj_main_loop().
rtc_read_register()
int rtc_read_register (uint8_t reg, uint8_t * data)
Reads the Register reg of the RTC.
Parameters
reg register number
data return data
Returns
int 1 if it fails, 0 otherwise
Definition at line 21 of file rtc.c.
References RTC_ADDR_REG, RTC_DATA_REG, and util_sys_inb().
Referenced by proj_main_loop(), rtc_ih(), rtc_read_time(), and rtc_set_periodic().
rtc_read_time()
int rtc_read_time (uint8_t * hours, uint8_t * minutes, uint8_t * seconds)
Reads the time from the RTC.
Parameters
hours address where the current hours will be written
minutes address where the current minutes will be written
seconds address where the current seconds will be written
Returns
int 1 if it fails, 0 otherwise
Definition at line 50 of file rtc.c.
References rtc_read_register(), RTC_REG_A, RTC_REG_H, RTC_REG_M, RTC_REG_S, and RTC_UIP.
Referenced by create_enemies(), rtc_ih(), and rtc_set_alarm_delta_s().
rtc_set_alarm()
int rtc_set_alarm (uint8_t hours, uint8_t minutes, uint8_t seconds)
Sets an alarm at hours : minutes : seconds.
Parameters
hours hour to set the alarm to
minutes minute to set the alarm to
seconds second to set the alarm to
Returns
int 1 if it fails, 0 otherwise
Definition at line 39 of file rtc.c.
References RTC_REG_H_A, RTC_REG_M_A, RTC_REG_S_A, and rtc_write_register().
Referenced by rtc_set_alarm_delta_s().
rtc_set_alarm_delta_s()
int rtc_set_alarm_delta_s (uint8_t delta_seconds)
Sets an alarm at current_time + delta_seconds.
Parameters
delta_seconds the number of seconds before the alarm will trigger
Returns
int 1 if it fails, 0 otherwise
Definition at line 79 of file rtc.c.
References bcd_to_binary(), binary_to_bcd(), rtc_read_time(), and rtc_set_alarm().
Referenced by spearman_special().
rtc_set_periodic()
int rtc_set_periodic (uint8_t delta_t)
Sets the periodic interrupts time to send interrupts every delta_t.
Parameters
delta_t time corresponding to the periodic interrupt specifications
Returns
int 1 if it fails, 0 otherwise
Definition at line 68 of file rtc.c.
References rtc_read_register(), RTC_REG_A, and rtc_write_register().
rtc_subscribe_int()
int() rtc_subscribe_int (uint8_t * bit_no)
Subscribes the RTC interrupts.
Returns
1 if it fails, 0 otherwise
Definition at line 10 of file rtc.c.
References IRQ_8, and rtc_hook_id.
Referenced by proj_main_loop().
rtc_unsubscribe_int()
int() rtc_unsubscribe_int ()
Unsubscribes the RTC interrupts.
Returns
1 if it fails, 0 otherwise
Definition at line 16 of file rtc.c.
References rtc_hook_id.
Referenced by proj_main_loop().
rtc_write_register()
int rtc_write_register (uint8_t reg, uint8_t data)
Writes to the Register reg of the RTC data.
Parameters
reg register number
data writing data
Returns
int 1 if it fails, 0 otherwise
Definition at line 30 of file rtc.c.
References RTC_ADDR_REG, and RTC_DATA_REG.
Referenced by proj_main_loop(), rtc_set_alarm(), and rtc_set_periodic().