Lowlife Champions of Mosscrest: utils.c File Reference
utils.c File Reference
#include <lcom/lcf.h>
#include <lcom/liblm.h>
#include <lcom/proj.h>
#include "utils.h"
Functions
int() util_sys_inb (int port, uint8_t *value)
Gets from port 8 bit information to value.
Function Documentation
util_sys_inb()
int() util_sys_inb (int port, uint8_t * value)
Gets from port 8 bit information to value.
Parameters
port port to get the information from
value return values for this input operation
Returns
int 1 if it fails 0 otherwise
Definition at line 6 of file utils.c.
Referenced by kbc_write_command(), kbd_parse_data(), mouse_ih(), mouse_write_command(), rtc_read_register(), send_data_uart(), and uart_ih().